image: registry.gitlab.isc.org/isc-projects/kea-docker:latest

variables:
  # Disables TLS for communication with docker.
  DOCKER_TLS_CERTDIR:

services:
  # This service runs the docker server.
  - docker:dind

.show-environment:
  before_script:
    - whoami
    - cat /etc/os-release
    - docker --version
    - docker-compose --version

dhcp4:
  extends: .show-environment
  script:
    # Change directory
    - cd kea-dhcp4
    # Build the image.
    - docker build -t kea-dhcp4 .
    # Run the dhcp4 container
    - docker run -d --name kea-dhcp4 kea-dhcp4
    # Check that something was logged.
    - sleep 5
    - docker logs kea-dhcp4 | grep "kea-agent entered RUNNING state"
    - docker logs kea-dhcp4 | grep "kea-dhcp4 entered RUNNING state"
    # Clean up, while also checking that the container can be stopped
    - docker stop kea-dhcp4

dhcp6:
  extends: .show-environment
  script:
    # Change directory
    - cd kea-dhcp6
    # Build the image.
    - docker build -t kea-dhcp6 .
    # Run the dhcp4 container
    - docker run -d --name kea-dhcp6 kea-dhcp6
    # Check that something was logged.
    - sleep 5
    - docker logs kea-dhcp6 | grep "kea-agent entered RUNNING state"
    - docker logs kea-dhcp6 | grep "kea-dhcp6 entered RUNNING state"
    # Clean up, while also checking that the container can be stopped
    - docker stop kea-dhcp6

ddns:
  extends: .show-environment
  script:
    # Change directory
    - cd kea-dhcp-ddns
    # Build the image.
    - docker build -t kea-dhcp-ddns .
    # Run the dhcp4 container
    - docker run -d --name kea-dhcp-ddns kea-dhcp-ddns
    # Check that something was logged.
    - sleep 5
    - docker logs kea-dhcp-ddns | grep "kea-agent entered RUNNING state"
    - docker logs kea-dhcp-ddns | grep "kea-dhcp-ddns entered RUNNING state"
    # Clean up, while also checking that the container can be stopped
    - docker stop kea-dhcp-ddns

hadolint:
  allow_failure: false
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint --ignore DL3018 kea-dhcp4/Dockerfile
    - hadolint --ignore DL3018 kea-dhcp6/Dockerfile
    - hadolint --ignore DL3018 kea-dhcp-ddns/Dockerfile
    # DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
