volumes:
  database:
  var:

services:
  kea4:
    image: kea-dhcp4:${VERSION}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kea-macvlan
      - kea-internal
    volumes:
      - type: bind
        source: ./config/kea
        target: /etc/kea
      - var:/var/lib/kea

  kea6:
    image: kea-dhcp6:${VERSION}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kea-macvlan
      # Comment above, and uncomment below for separate v4 and v6 interface
      # kea6-macvlan
      - kea-internal
    volumes:
      - type: bind
        source: ./config/kea
        target: /etc/kea
      - var:/var/lib/kea

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -U keadb -d keadb -c 'SELECT version FROM schema_version'"]
    environment:
      POSTGRES_PASSWORD: keatest
      POSTGRES_USER: keadb
    networks:
      - kea-internal
    volumes:
      - database:/var/lib/posgresql
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d

networks:
  kea-macvlan:
    name: kea-macvlan
    driver: macvlan
    driver_opts:
      parent: ${ETH}
# Uncomment section below for separate v4 and v6 interface
#  kea6-macvlan:
#    name: kea6-macvlan
#    driver: macvlan
#    driver_opts:
#      parent: ${ETH6}
  kea-internal:
    name: kea-internal
