name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
    - uses: docker/login-action@v3.4.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      working-directory: ./kea-dhcp4
      run: docker build . --file Dockerfile --tag ${{ IMAGE_NAME }}:$(date +%s)

    - name: Build and push
    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ IMAGE_NAME }}:$(date +%s)
